#!/usr/bin/env bash
# Install this repo's git hooks. Run once per clone.
#
# The pre-commit hook refuses hand-edits to custom_components/, which is
# GENERATED by brand-gen in the canonical Dashie repo and destroyed by the next
# regeneration. Without it, an edit here commits and reviews normally, then
# vanishes with no error.
set -euo pipefail
cd "$(dirname "$0")/.."
ln -sf ../../scripts/hooks/pre-commit .git/hooks/pre-commit
chmod +x scripts/hooks/pre-commit
echo "✅ hooks installed (pre-commit: refuses hand-edits to generated trees)"
